name: ci

on:
  push:
    branches: main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sattlerj/wc-frontend:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/wc
            ls -la
            docker-compose stop wc-frontend
            docker-compose rm -f wc-frontend
            docker-compose pull wc-frontend
            docker-compose up -d wc-frontend
